version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.cloud.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.cloud.local:8000'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['initial_root_password'] = "MySuperSecretAndSecurePassw0rd!"
        gitlab_rails['gitlab_shell_ssh_port'] = 7800
    ports:
      - '8000:8000'
      #- '443:443'
      - '7800:7800'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

  gitlab_docs:
    image: registry.gitlab.com/gitlab-org/gitlab-docs:14.5
    hostname: 'https://docs.gitlab.cloud.local:4000'
    ports:
      - '4000:4000'